version: "3"

services:
  app:
    build: .
    environment:
      - EXTERNAL_DOMAIN=foo.bar
      - VPC_DOMAIN=vpc-xyx.us-east1.com
    restart: always
    ports:
      - "80:80"
      - "8080:8080"
